Move the skeleton to the bleeding edge
NetherlandsForensicInstitute/hansken-extraction-plugin-template-python pull request #2
Opened 2021-08-09 11:09 UTC by bartbroere

As mentioned in @remco-nfi 's release notes, these changes need to be made to support the latest SDK version (0.2.0).

2021-08-09 19:24 UTC, remco-nfi commented
Thanks for the PR!
Can you please update the SDK version to `0.3.0` in setup.py?

2021-08-09 19:26 UTC, remco-nfi requested changes

2021-08-09 19:26 UTC, remco-nfi commented on plugin/extraction_plugin.py
> +from hansken_extraction_plugin.api.plugin_info import Author, PluginInfo, MaturityLevel
```suggestion
from hansken_extraction_plugin.api.plugin_info import Author, MaturityLevel, PluginInfo
```

2021-08-10 11:34 UTC, bartbroere commented
> Thanks for the PR!
> Can you please update the SDK version to `0.3.0` in setup.py?

Yes, done!

2021-08-10 11:41 UTC, bartbroere commented
I think we're done. Feel free to merge it if it looks okay like this.

2021-08-11 06:28 UTC, merged

2021-08-11 06:29 UTC, remco-nfi commented
Looks great! Thanks!